kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins
subjects:
- kind: User
  # Change your account details below
  name: rajnivas.n
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""